---
- name: Copy redshift config to host
  copy:
    src: redshift.conf
    dest: "{{ ansible_env.HOME }}/.config/redshift.conf"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0644
...

