---
- name: Update system
  zypper:
    name: "*"
    state: dist-upgrade

- name: Install packages
  zypper:
    name: ["zsh", "tmux", "htop", "vim", "git", "docker", "docker-compose", "redshift", "redshift-gtk", "python3-pip"]
    state: present
...
