---
- name: Update system
  become: yes
  zypper:
    name: "*"
    state: dist-upgrade

- name: Install packages
  become: yes
  zypper:
    name: 
      - zsh
      - tmux
      - htop
      - neovim
      - git
      - ripgrep
      - fd
      - stow
      - alacritty
      - docker
      - docker-compose
    state: present
...

