---
  - name: Install vundle
    git:
      repo: https://github.com/VundleVim/Vundle.vim.git
      dest: ~/.vim/bundle/Vundle.vim

  - name: Install vundle extensions
    shell: vim +PluginInstall +qall
...

