---
- name: Create .ssh folder
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh"
    mode: '0700'
    state: directory
- name: Generate SSH key
  community.crypto.openssh_keypair:
      path: ~/.ssh/id_ed25519
      type: ed25519
      size: 4096

