---
- name: Download prezto
  git:
    repo: https://github.com/JustinKnueppel/prezto.git
    dest: ~/.zprezto
    recursive: yes
  
- name: Link config files
  script: copy_zsh_files.zsh
  args:
    executable: /usr/bin/env zsh

- name: Make zsh default
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
...